# Form implementation generated from reading ui file 'c:\Alunos\ThaizaFavarelli\pyqt\pedrapapel_menu_jVelha\qt designer\jogo_joken_po.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 530)
        Form.setMinimumSize(QtCore.QSize(450, 530))
        Form.setMaximumSize(QtCore.QSize(450, 530))
        Form.setStyleSheet("background-color:rgb(134, 186, 255);")
        self.titulo = QtWidgets.QLabel(Form)
        self.titulo.setGeometry(QtCore.QRect(140, 30, 201, 61))
        self.titulo.setStyleSheet("font: 75 19pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n"
"")
        self.titulo.setObjectName("titulo")
        self.btn_pedra = QtWidgets.QPushButton(Form)
        self.btn_pedra.setGeometry(QtCore.QRect(50, 170, 101, 71))
        self.btn_pedra.setStyleSheet("background-color:rgb(127, 127, 127);")
        self.btn_pedra.setObjectName("btn_pedra")
        self.btn_papel = QtWidgets.QPushButton(Form)
        self.btn_papel.setGeometry(QtCore.QRect(170, 170, 101, 71))
        self.btn_papel.setStyleSheet("background-color:rgb(214, 214, 214);")
        self.btn_papel.setObjectName("btn_papel")
        self.btn_tesoura = QtWidgets.QPushButton(Form)
        self.btn_tesoura.setGeometry(QtCore.QRect(300, 170, 101, 71))
        self.btn_tesoura.setStyleSheet("background-color:rgb(200, 87, 67);")
        self.btn_tesoura.setObjectName("btn_tesoura")
        self.resposta = QtWidgets.QLabel(Form)
        self.resposta.setGeometry(QtCore.QRect(60, 280, 331, 111))
        self.resposta.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.resposta.setText("")
        self.resposta.setObjectName("resposta")
        self.btn_reset = QtWidgets.QPushButton(Form)
        self.btn_reset.setGeometry(QtCore.QRect(160, 420, 111, 61))
        self.btn_reset.setStyleSheet("background-color:rgb(143, 150, 158);")
        self.btn_reset.setObjectName("btn_reset")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.titulo.setText(_translate("Form", "Jogo Joken Po!"))
        self.btn_pedra.setText(_translate("Form", "Pedra"))
        self.btn_papel.setText(_translate("Form", "Papel"))
        self.btn_tesoura.setText(_translate("Form", "Tesoura"))
        self.btn_reset.setText(_translate("Form", "Resetar"))
