# Form implementation generated from reading ui file 'c:\Alunos\ThaizaFavarelli\pyqt\pedrapapel_menu_jVelha\qt_designer\jogo_da_forca.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormForca(object):
    def setupUi(self, FormForca):
        FormForca.setObjectName("FormForca")
        FormForca.setEnabled(True)
        FormForca.resize(450, 530)
        FormForca.setMinimumSize(QtCore.QSize(450, 530))
        FormForca.setMaximumSize(QtCore.QSize(450, 530))
        FormForca.setStyleSheet("background-color:rgb(139, 139, 139);\n"
"")
        self.png_forca = QtWidgets.QLabel(FormForca)
        self.png_forca.setGeometry(QtCore.QRect(0, 70, 231, 281))
        self.png_forca.setText("")
        self.png_forca.setPixmap(QtGui.QPixmap("c:\\Alunos\\ThaizaFavarelli\\pyqt\\pedrapapel_menu_jVelha\\qt_designer\\../forca.png"))
        self.png_forca.setScaledContents(True)
        self.png_forca.setObjectName("png_forca")
        self.titulo = QtWidgets.QLabel(FormForca)
        self.titulo.setGeometry(QtCore.QRect(130, 10, 211, 61))
        self.titulo.setStyleSheet("font: 75 18pt \"Myanmar Text\";\n"
"text-decoration: underline;\n"
"font: 24pt \"MS Shell Dlg 2\";")
        self.titulo.setText("")
        self.titulo.setObjectName("titulo")
        self.dicas = QtWidgets.QLabel(FormForca)
        self.dicas.setGeometry(QtCore.QRect(250, 420, 171, 51))
        self.dicas.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.dicas.setText("")
        self.dicas.setObjectName("dicas")
        self.letras_underlines = QtWidgets.QLabel(FormForca)
        self.letras_underlines.setGeometry(QtCore.QRect(40, 360, 351, 51))
        self.letras_underlines.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.letras_underlines.setText("")
        self.letras_underlines.setObjectName("letras_underlines")
        self.cabeca = QtWidgets.QLabel(FormForca)
        self.cabeca.setEnabled(False)
        self.cabeca.setGeometry(QtCore.QRect(170, 190, 51, 51))
        self.cabeca.setText("")
        self.cabeca.setPixmap(QtGui.QPixmap("c:\\Alunos\\ThaizaFavarelli\\pyqt\\pedrapapel_menu_jVelha\\qt_designer\\../cabeca.png"))
        self.cabeca.setScaledContents(True)
        self.cabeca.setObjectName("cabeca")
        self.tronco = QtWidgets.QLabel(FormForca)
        self.tronco.setEnabled(False)
        self.tronco.setGeometry(QtCore.QRect(180, 240, 31, 61))
        self.tronco.setText("")
        self.tronco.setPixmap(QtGui.QPixmap("c:\\Alunos\\ThaizaFavarelli\\pyqt\\pedrapapel_menu_jVelha\\qt_designer\\../tronco.png"))
        self.tronco.setScaledContents(True)
        self.tronco.setObjectName("tronco")
        self.b_direito = QtWidgets.QLabel(FormForca)
        self.b_direito.setEnabled(False)
        self.b_direito.setGeometry(QtCore.QRect(210, 240, 21, 51))
        self.b_direito.setText("")
        self.b_direito.setPixmap(QtGui.QPixmap("c:\\Alunos\\ThaizaFavarelli\\pyqt\\pedrapapel_menu_jVelha\\qt_designer\\../b_direito.png"))
        self.b_direito.setScaledContents(True)
        self.b_direito.setObjectName("b_direito")
        self.b_esquerdo = QtWidgets.QLabel(FormForca)
        self.b_esquerdo.setEnabled(False)
        self.b_esquerdo.setGeometry(QtCore.QRect(160, 250, 21, 41))
        self.b_esquerdo.setText("")
        self.b_esquerdo.setPixmap(QtGui.QPixmap("c:\\Alunos\\ThaizaFavarelli\\pyqt\\pedrapapel_menu_jVelha\\qt_designer\\../b_esquerdo.png"))
        self.b_esquerdo.setScaledContents(True)
        self.b_esquerdo.setObjectName("b_esquerdo")
        self.p_direita = QtWidgets.QLabel(FormForca)
        self.p_direita.setEnabled(False)
        self.p_direita.setGeometry(QtCore.QRect(200, 300, 21, 41))
        self.p_direita.setText("")
        self.p_direita.setPixmap(QtGui.QPixmap("c:\\Alunos\\ThaizaFavarelli\\pyqt\\pedrapapel_menu_jVelha\\qt_designer\\../p_direita.png"))
        self.p_direita.setScaledContents(True)
        self.p_direita.setObjectName("p_direita")
        self.p_esquerda = QtWidgets.QLabel(FormForca)
        self.p_esquerda.setEnabled(False)
        self.p_esquerda.setGeometry(QtCore.QRect(170, 300, 21, 41))
        self.p_esquerda.setText("")
        self.p_esquerda.setPixmap(QtGui.QPixmap("c:\\Alunos\\ThaizaFavarelli\\pyqt\\pedrapapel_menu_jVelha\\qt_designer\\../p_esquerda.png"))
        self.p_esquerda.setScaledContents(True)
        self.p_esquerda.setObjectName("p_esquerda")
        self.btn_chutar = QtWidgets.QPushButton(FormForca)
        self.btn_chutar.setGeometry(QtCore.QRect(180, 480, 91, 41))
        self.btn_chutar.setObjectName("btn_chutar")
        self.chute = QtWidgets.QLineEdit(FormForca)
        self.chute.setGeometry(QtCore.QRect(40, 420, 181, 51))
        self.chute.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.chute.setObjectName("chute")

        self.retranslateUi(FormForca)
        QtCore.QMetaObject.connectSlotsByName(FormForca)

    def retranslateUi(self, FormForca):
        _translate = QtCore.QCoreApplication.translate
        FormForca.setWindowTitle(_translate("FormForca", "Form"))
        self.btn_chutar.setText(_translate("FormForca", "jogar"))
