# Form implementation generated from reading ui file 'c:\Alunos\ThaizaFavarelli\pyqt\pedrapapel_menu_jVelha\qt_designer\velha.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(577, 485)
        Form.setWindowTitle("")
        Form.setStyleSheet("background-color: rgb(139, 139, 139);")
        self.btn8 = QtWidgets.QPushButton(Form)
        self.btn8.setGeometry(QtCore.QRect(250, 339, 71, 61))
        self.btn8.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(140, 0, 255, 255), stop:0.55 rgba(105,105,105,255), stop:0.98 rgba(0, 0, 0), stop:1 rgba(0, 0, 0));\n"
"border-radius: 10px;\n"
"color: white;")
        self.btn8.setText("")
        self.btn8.setObjectName("btn8")
        self.btn4 = QtWidgets.QPushButton(Form)
        self.btn4.setGeometry(QtCore.QRect(140, 239, 71, 61))
        self.btn4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(140, 0, 255, 255), stop:0.55 rgba(105,105,105,255), stop:0.98 rgba(0, 0, 0), stop:1 rgba(0, 0, 0));\n"
"border-radius: 10px;\n"
"color: white;")
        self.btn4.setText("")
        self.btn4.setObjectName("btn4")
        self.btn7 = QtWidgets.QPushButton(Form)
        self.btn7.setGeometry(QtCore.QRect(140, 339, 71, 61))
        self.btn7.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(140, 0, 255, 255), stop:0.55 rgba(105,105,105,255), stop:0.98 rgba(0, 0, 0), stop:1 rgba(0, 0, 0));\n"
"border-radius: 10px;\n"
"color: white;")
        self.btn7.setText("")
        self.btn7.setObjectName("btn7")
        self.btn6 = QtWidgets.QPushButton(Form)
        self.btn6.setGeometry(QtCore.QRect(360, 239, 71, 61))
        self.btn6.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(140, 0, 255, 255), stop:0.55 rgba(105,105,105,255), stop:0.98 rgba(0, 0, 0), stop:1 rgba(0, 0, 0));\n"
"border-radius: 10px;\n"
"color: white;")
        self.btn6.setText("")
        self.btn6.setObjectName("btn6")
        self.btn1 = QtWidgets.QPushButton(Form)
        self.btn1.setGeometry(QtCore.QRect(140, 139, 71, 61))
        self.btn1.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(140, 0, 255, 255), stop:0.55 rgba(105,105,105,255), stop:0.98 rgba(0, 0, 0), stop:1 rgba(0, 0, 0));\n"
"border-radius: 10px;\n"
"color: white;")
        self.btn1.setText("")
        self.btn1.setObjectName("btn1")
        self.btn9 = QtWidgets.QPushButton(Form)
        self.btn9.setGeometry(QtCore.QRect(360, 339, 71, 61))
        self.btn9.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(140, 0, 255, 255), stop:0.55 rgba(105,105,105,255), stop:0.98 rgba(0, 0, 0), stop:1 rgba(0, 0, 0));\n"
"border-radius: 10px;\n"
"color: white;")
        self.btn9.setText("")
        self.btn9.setObjectName("btn9")
        self.btn5 = QtWidgets.QPushButton(Form)
        self.btn5.setGeometry(QtCore.QRect(250, 239, 71, 61))
        self.btn5.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(140, 0, 255, 255), stop:0.55 rgba(105,105,105,255), stop:0.98 rgba(0, 0, 0), stop:1 rgba(0, 0, 0));\n"
"border-radius: 10px;\n"
"color: white;")
        self.btn5.setText("")
        self.btn5.setObjectName("btn5")
        self.btn3 = QtWidgets.QPushButton(Form)
        self.btn3.setGeometry(QtCore.QRect(360, 139, 71, 61))
        self.btn3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(140, 0, 255, 255), stop:0.55 rgba(105,105,105,255), stop:0.98 rgba(0, 0, 0), stop:1 rgba(0, 0, 0));\n"
"border-radius: 10px;\n"
"color: white;\n"
"\n"
"")
        self.btn3.setText("")
        self.btn3.setObjectName("btn3")
        self.btn2 = QtWidgets.QPushButton(Form)
        self.btn2.setGeometry(QtCore.QRect(250, 139, 71, 61))
        self.btn2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(140, 0, 255, 255), stop:0.55 rgba(105,105,105,255), stop:0.98 rgba(0, 0, 0), stop:1 rgba(0, 0, 0));\n"
"border-radius: 10px;\n"
"color: white;")
        self.btn2.setText("")
        self.btn2.setObjectName("btn2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(100, 40, 411, 61))
        font = QtGui.QFont()
        font.setFamily("Wide Latin")
        font.setPointSize(-1)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font-size: 35px;\n"
"color:white;")
        self.label_3.setObjectName("label_3")
        self.win = QtWidgets.QLabel(Form)
        self.win.setGeometry(QtCore.QRect(180, 410, 241, 91))
        self.win.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 25px;")
        self.win.setObjectName("win")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(220, 120, 21, 311))
        self.pushButton.setStyleSheet("border-radius: 10px;\n"
"background-color: black;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 119, 21, 311))
        self.pushButton_2.setStyleSheet("border-radius: 10px;\n"
"background-color: black;")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(130, 309, 321, 16))
        self.pushButton_3.setStyleSheet("border-radius: 10px;\n"
"background-color: black;")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(120, 210, 321, 16))
        self.pushButton_4.setStyleSheet("border-radius: 10px;\n"
"background-color: black;")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.label_3.setText(_translate("Form", "Jogo da Velha"))
        self.win.setText(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
